// IPC Channel definitions for main-renderer process communication

export const IPC_CHANNELS = {
  // Media Management
  IMPORT_MEDIA: 'IMPORT_MEDIA',
  IMPORT_MEDIA_DIALOG: 'IMPORT_MEDIA_DIALOG',
  EXPORT_MEDIA: 'EXPORT_MEDIA',
  GET_MEDIA_INFO: 'GET_MEDIA_INFO',
  DELETE_MEDIA: 'DELETE_MEDIA',
  
  // Timeline Operations
  TRIM_CLIP: 'TRIM_CLIP',
  SPLIT_CLIP: 'SPLIT_CLIP',
  MOVE_CLIP: 'MOVE_CLIP',
  DELETE_CLIP: 'DELETE_CLIP',
  DUPLICATE_CLIP: 'DUPLICATE_CLIP',
  UPDATE_CLIP_PROPERTIES: 'UPDATE_CLIP_PROPERTIES',
  
  // Effects & Transitions
  ADD_EFFECT: 'ADD_EFFECT',
  REMOVE_EFFECT: 'REMOVE_EFFECT',
  UPDATE_EFFECT: 'UPDATE_EFFECT',
  ADD_TRANSITION: 'ADD_TRANSITION',
  REMOVE_TRANSITION: 'REMOVE_TRANSITION',
  ADD_TEXT_OVERLAY: 'ADD_TEXT_OVERLAY',
  UPDATE_TEXT_OVERLAY: 'UPDATE_TEXT_OVERLAY',
  
  // Audio
  ADJUST_AUDIO_VOLUME: 'ADJUST_AUDIO_VOLUME',
  AUDIO_DUCKING: 'AUDIO_DUCKING',
  VOICE_ENHANCEMENT: 'VOICE_ENHANCEMENT',
  AUDIO_NORMALIZE: 'AUDIO_NORMALIZE',
  AUDIO_SYNC: 'AUDIO_SYNC',
  
  // Export & Rendering
  RENDER_PROJECT: 'RENDER_PROJECT',
  EXPORT_START: 'EXPORT_START',
  EXPORT_PROGRESS: 'EXPORT_PROGRESS',
  EXPORT_COMPLETE: 'EXPORT_COMPLETE',
  EXPORT_ERROR: 'EXPORT_ERROR',
  EXPORT_CANCEL: 'EXPORT_CANCEL',
  EXPORT_QUEUE_ADD: 'EXPORT_QUEUE_ADD',
  EXPORT_QUEUE_REMOVE: 'EXPORT_QUEUE_REMOVE',
  EXPORT_PRESET_SAVE: 'EXPORT_PRESET_SAVE',
  EXPORT_PRESET_DELETE: 'EXPORT_PRESET_DELETE',
  EXPORT_PRESET_LOAD: 'EXPORT_PRESET_LOAD',
  EXPORT_PRESET_MANAGER: 'EXPORT_PRESET_MANAGER',
  
  // Performance & Optimization
  GENERATE_PROXY: 'GENERATE_PROXY',
  PROXY_PROGRESS: 'PROXY_PROGRESS',
  PROXY_COMPLETE: 'PROXY_COMPLETE',
  GENERATE_THUMBNAIL: 'GENERATE_THUMBNAIL',
  THUMBNAIL_COMPLETE: 'THUMBNAIL_COMPLETE',
  GENERATE_WAVEFORM: 'GENERATE_WAVEFORM',
  WAVEFORM_COMPLETE: 'WAVEFORM_COMPLETE',
  
  // Project Management
  PROJECT_NEW: 'PROJECT_NEW',
  PROJECT_OPEN: 'PROJECT_OPEN',
  PROJECT_SAVE: 'PROJECT_SAVE',
  PROJECT_SAVE_AS: 'PROJECT_SAVE_AS',
  PROJECT_CLOSE: 'PROJECT_CLOSE',
  PROJECT_AUTO_SAVE: 'PROJECT_AUTO_SAVE',
  GET_PROJECT_SNAPSHOT: 'GET_PROJECT_SNAPSHOT',
  PROJECT_LOAD_TEMPLATE: 'PROJECT_LOAD_TEMPLATE',
  
  // Recovery & History
  RECOVER_PROJECT: 'RECOVER_PROJECT',
  RECOVERY_DATA_SAVE: 'RECOVERY_DATA_SAVE',
  RECOVERY_DATA_LOAD: 'RECOVERY_DATA_LOAD',
  UNDO: 'UNDO',
  REDO: 'REDO',
  
  // Smart Tools
  SMART_CUT: 'SMART_CUT',
  SMART_CUT_PREVIEW: 'SMART_CUT_PREVIEW',
  SMART_CUT_APPLY: 'SMART_CUT_APPLY',
  JUMP_CUT: 'JUMP_CUT',
  JUMP_CUT_MARK: 'JUMP_CUT_MARK',
  SCENE_CUT_DETECTION: 'SCENE_CUT_DETECTION',
  AUTO_REFRAME: 'AUTO_REFRAME',
  AUTO_THUMBNAIL_PICKER: 'AUTO_THUMBNAIL_PICKER',
  DETECT_SHAKY_FOOTAGE: 'DETECT_SHAKY_FOOTAGE',
  
  // Color & Visual
  COLOR_MATCHING: 'COLOR_MATCHING',
  COLOR_GRADE_APPLY: 'COLOR_GRADE_APPLY',
  LUT_LOAD: 'LUT_LOAD',
  
  // Clipboard
  CLIPBOARD_COPY: 'CLIPBOARD_COPY',
  CLIPBOARD_PASTE: 'CLIPBOARD_PASTE',
  CLIPBOARD_CUT: 'CLIPBOARD_CUT',
  CLIPBOARD_HISTORY: 'CLIPBOARD_HISTORY',
  CLIPBOARD_HISTORY_GET: 'CLIPBOARD_HISTORY_GET',
  
  // Hardware & Settings
  HARDWARE_INFO_GET: 'HARDWARE_INFO_GET',
  HARDWARE_ACCEL_DETECT: 'HARDWARE_ACCEL_DETECT',
  HARDWARE_ACCEL_SET: 'HARDWARE_ACCEL_SET',
  PREFERENCES_GET: 'PREFERENCES_GET',
  PREFERENCES_SET: 'PREFERENCES_SET',
  CACHE_CLEAR: 'CACHE_CLEAR',
  CACHE_SIZE_GET: 'CACHE_SIZE_GET',
  
  // Performance Monitoring
  PERFORMANCE_METRICS_GET: 'PERFORMANCE_METRICS_GET',
  MEMORY_WARNING: 'MEMORY_WARNING',
  MEMORY_CLEANUP: 'MEMORY_CLEANUP',
  
  // FFmpeg Tasks
  FFMPEG_TASK_START: 'FFMPEG_TASK_START',
  FFMPEG_TASK_PROGRESS: 'FFMPEG_TASK_PROGRESS',
  FFMPEG_TASK_COMPLETE: 'FFMPEG_TASK_COMPLETE',
  FFMPEG_TASK_ERROR: 'FFMPEG_TASK_ERROR',
  FFMPEG_VALIDATE: 'FFMPEG_VALIDATE',
  FFMPEG_VERSION_GET: 'FFMPEG_VERSION_GET',
  
  // File System
  FILE_DIALOG_OPEN: 'FILE_DIALOG_OPEN',
  FILE_DIALOG_SAVE: 'FILE_DIALOG_SAVE',
  FILE_EXISTS: 'FILE_EXISTS',
  FILE_RELINK: 'FILE_RELINK',
  FILE_RELINK_BATCH: 'FILE_RELINK_BATCH',
  
  // Logging & Debug
  LOG_INFO: 'LOG_INFO',
  LOG_ERROR: 'LOG_ERROR',
  LOG_WARNING: 'LOG_WARNING',
  DEBUG_TIMELINE_STATE: 'DEBUG_TIMELINE_STATE',
  FEATURE_FLAG_GET: 'FEATURE_FLAG_GET',
  FEATURE_FLAG_SET: 'FEATURE_FLAG_SET',
};